# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


# CUSTOM PS1 VARIABLE 
PS1='\[\033[01;34m\]\W\[\033[00m\] -> '

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

cd /mnt/c/Users/nobel

function ld {
	ls $@ 2> /dev/null
}

alias ls=ld

function cs {
	cd $@ && ls
}

# my aliases 
alias cd=cs
alias refresh="source ~/.bashrc"
alias cdh="cd /mnt/c/Users/nobel"
alias update="sudo apt update && sudo apt upgrade -y"
alias open="cygstart.exe"
alias erc="vim ~/.bashrc"
alias b="cd .."
alias bk="cd -"
alias grep="grep --color"
alias x="exit"
alias c="clear"
alias idea="idea64.exe"
alias s="ls | grep -i"
alias ff="find . -type f -iname"
alias fd="find . -type d -iname"
alias tm="tmux"
alias tls="tmux ls"
alias ta="tmux attach"
alias tks="tmux kill-server"
alias ainst="sudo apt install"
alias arm="sudo apt remove"
alias updrc="/mnt/c/Users/nobel/i3-dotfiles/update_repo.sh"

# git aliases
alias g="git"
alias gs="git status"
alias ga="git add"
alias gaa="git add ."
alias gcm="git commit -m"
alias gca="git commit -a"
alias gcam="git commit -am"
alias gp="git pull"
alias gsh="git stash"
alias gshd="git stash drop"
alias gsu="git status -uno"

LS_COLORS=$LS_COLORS:'ow=1;34:' ; export LS_COLORS

# auto start tmux (personal use only) 
tmux attach &> /dev/null

# if [[ ! $TERM =~ screen ]]; then
# 	    exec tmux
# fi

