set number
set ignorecase
set incsearch
set relativenumber
set backspace=2
set wrap
syntax on

colorscheme slate

noremap! <C-BS> <C-w>
noremap! <C-h> <C-w>

nnoremap <space> i<space><esc>l
nnoremap <return> o<esc>
nnoremap <S-return> O<esc>
nnoremap J <C-e>
nnoremap K <C-y>

vnoremap <C-C> "+y
map <C-V> "+gP

autocmd GUIEnter * simalt ~x
set guifont=Lucida\ Console:h12
